version: '3'

services:
  front_end: 
    image: 1_14_front
    ports:
      - 5000:5000
  cache:
    image: redis
    ports:
      - 6379:6379
  back_end:
    image: 1_14_back
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=cache
    