FROM mhart/alpine-node:12
WORKDIR /app/expressdevops
COPY . ./
ENV NODE_ENV=production
RUN npm install --only=prod && \
    chmod a+x /app/expressdevops && adduser -D appuser
USER appuser
EXPOSE 3000
CMD ["npm", "start"]